import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Setup',
      items: [
        'debugging-protocol',
        'profiling-engine',
        'asset-hot-reload',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture',
        'security-posture',
        'v2-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Lifecycle',
      items: [
        'development-lifecycle',
        'quality-assurance',
        'release-ops',
        'audit-signoff',
        'developer-lifecycle',
      ],
    },
    {
      type: 'category',
      label: 'API Reference (TypeScript)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-ts',
        },
      ],
    },
    {
      type: 'category',
      label: 'v2.0 Roadmap',
      items: [
        'roadmap-v1',
        'v2-roadmap',
      ],
    },
  ],
};

export default sidebars;
